[build]
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "esbuild"

[functions."publish-wordpress"]
  timeout = 26
  external_node_modules = ["@sparticuz/chromium"]
  included_files = ["node_modules/@sparticuz/chromium/bin/**"]
