[build]
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "esbuild"

[functions."generate-articles"]
  timeout = 26

[functions."publish-wordpress"]
  timeout = 26
  external_node_modules = ["@sparticuz/chromium-min"]
